name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # æ‰‹å‹•è§¸ç™¼

jobs:
  explore_github_actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Triggered by ${{ github.event_name }} event."
      - run: echo "ğŸ§ Running on ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ Repository cloned to ${{ github.workspace }}."
      - run: echo "ğŸ–¥ï¸ Ready to test your code on the runner."
      - name: List files
        run: ls ${{ github.workspace }}
      - run: echo "ğŸ Job status is ${{ job.status }}."
